eureka:
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true
server:
  port: 20260
spring:
  application:
    name: pipeline-server
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    function:
      definition: processProduct;processMessage;processProductDetail
    stream:
      bindings:
        processProductDetail-in-0:
          destination: product-detail # topic_name
          group: monitor-group2 #consumer_group_id
          content-type: application/json
        processProduct-in-0:
          destination: test-product
          group: monitor-group
          content-type: application/json
        processMessage-in-0:
          destination: test-topic
        processProductDetail-out-0:
          destination: processed-product-detail
          content-type: application/json
      Kafka:
        binder:
          brokers: localhost:29092,localhost:29094,localhost:29096
          configuration:
            auto.offset.reset: earliest
  #      kafka:
#        binder:
#          brokers: localhost:29092,localhost:29094,localhost:29096
#          configuration:
#            auto.offset.reset: earliest
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090
      client:
        provider:
          itp-standard:
            issuer-uri: http://localhost:9090
        registration:
          itp-standard:
            provider: itp-standard
            client-id: itp-standard
            client-secret: qwerqwer
            # redirect to gateway server
            redirect-uri: http://localhost:9999/login/oauth2/code/itp-standard
            authorization-grant-type: client_credentials
            scope:
              - openid # Auto issue access token
              - profile # Get profile
              - email # Get email

resilience4j:
  circuitbreaker:
    instances:
      account:
        sliding-window-size: 10
        failure-rate-threshold: 50
        permitted-number-of-calls-in-half-open-state: 2
        wait-duration-in-open-state: 10000

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    hongleap.pipeline_service: DEBUG